apiVersion: v1
kind: Secret
metadata:
  name: postgres-process-secret
type: Opaque
data:
  POSTGRES_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  POSTGRES_USER: cHJvY2Vzcw== #process
  POSTGRES_PASSWORD: dGVzdDEyMw== #test123
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-report-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-report
  labels:
    app: postgres-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-report
  template:
    metadata:
      labels:
        app: postgres-report
    spec:
      containers:
        - image: postgres:14.1-alpine
          name: postgres-report
          env:
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-report-secret
                  key: POSTGRES_ROOT_PASSWORD
            - name: POSTGRES_DATABASE
              value: report
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-report-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-report-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 3306
              name: postgres-process
          volumeMounts:
            - name: postgress-report-persistent-storage
              mountPath: /var/lib/postgres
      volumes:
        - name: postgres-report-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-report-volumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-report
  labels:
    app: postgres-report
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: postgres-report