apiVersion: v1
kind: Service
metadata:
  name: robot-ms
  labels:
    app: robot-apocalypse
    tier: robot-ms
spec:
  type: LoadBalancer
  ports:
    - port: 9001
  selector:
    app: robot-apocalypse
    tier: survivor-ms